import { SarDataset, ChatSession } from "./types";

export const SAR_DATASETS: SarDataset[] = [
  {
    id: "ship_detection",
    title: "Maritime Vessel Target Reconnaissance & AIS Verification",
    location: "Strait of Malacca / Singapore Anchorage",
    country: "International Waters",
    coordinates: {
      lat: "1°14'22.4\"N",
      lon: "103°55'18.8\"E",
    },
    filename: "sar_geotiff_03_ship_detection_umbra.tif",
    imageSrc: "/sar-samples/sar_geotiff_03_ship_detection_umbra.jpg",
    fileSize: "10.2 MB (GeoTIFF)",
    sensor: "Umbra X-SAR Constellation",
    mode: "High-Resolution Spotlight",
    polarization: "Single-Pol VV (Vertical Co-Pol)",
    resolution: "0.50 m GSD",
    frequency: "X-Band (9.6 GHz)",
    acquisitionDate: "2026-08-14 03:22:15 UTC",
    defaultPrompt:
      "Isolate all surface maritime vessels in the designated shipping channel. Estimate vessel lengths, detect radar double-bounce reflections, and flag any dark uncooperative targets not transmitting AIS.",
    suggestedPrompts: [
      "Detect all commercial cargo vessels and estimate hull displacement length.",
      "Identify dark vessels exhibiting high backscatter without AIS transponder correlation.",
      "Calculate sea clutter mean backscatter and flag wake dispersion patterns.",
      "Analyze multi-look radar coherence along the main navigation lane.",
    ],
    summary:
      "High-resolution 0.5m Spotlight SAR capture covering 2.4 km² anchorage sector with 14 isolated metallic surface targets and calm sea clutter baseline.",
    metrics: {
      totalTargets: 14,
      meanBackscatter: "-21.4 dBσ₀ (Sea Clutter)",
      peakBackscatter: "+24.2 dBσ₀ (Dihedral Hull)",
      surfaceArea: "2.40 km² Footprint",
      confidenceScore: "97.8% Multimodal Match",
    },
    detections: [
      {
        id: "det-1",
        label: "Container Carrier (L: 245m)",
        category: "vessel",
        confidence: 0.98,
        x: 46.5,
        y: 49.2,
        width: 14.5,
        height: 7.2,
        details: "Strong metallic corner reflection from cargo deck gantry structure.",
        metrics: { length: "245m", beam: "32m", backscatterDb: 22.4, rcs: "46.2 dBsm" },
      },
      {
        id: "det-2",
        label: "Crude Oil Tanker (L: 180m)",
        category: "vessel",
        confidence: 0.95,
        x: 28.2,
        y: 33.8,
        width: 11.2,
        height: 6.4,
        details: "Dihedral reflection between hull freeboard and sea surface boundary.",
        metrics: { length: "180m", beam: "28m", backscatterDb: 19.8, rcs: "39.5 dBsm" },
      },
      {
        id: "det-3",
        label: "Uncooperative Dark Vessel [FLAGGED]",
        category: "anomaly",
        confidence: 0.94,
        x: 64.0,
        y: 71.5,
        width: 8.5,
        height: 5.1,
        details: "High radar cross-section without AIS transponder signal match. Suspected dark fleet.",
        metrics: { length: "85m", beam: "14m", backscatterDb: 18.2, rcs: "32.1 dBsm" },
      },
      {
        id: "det-4",
        label: "Bulk Cargo Carrier (L: 160m)",
        category: "vessel",
        confidence: 0.96,
        x: 18.5,
        y: 76.0,
        width: 10.0,
        height: 5.8,
        details: "Prominent superstructure return with clear radar shadow offset.",
        metrics: { length: "160m", beam: "25m", backscatterDb: 21.0, rcs: "37.4 dBsm" },
      },
      {
        id: "det-5",
        label: "Tug / Offshore Support Vessel",
        category: "vessel",
        confidence: 0.91,
        x: 74.2,
        y: 22.4,
        width: 6.8,
        height: 4.5,
        details: "Compact radar centroid with distinct bow wake turbulence signature.",
        metrics: { length: "42m", beam: "11m", backscatterDb: 14.6, rcs: "22.8 dBsm" },
      },
    ],
    analysisFindings: {
      executiveSummary:
        "Automated SAR target extraction isolated 14 active marine vessels within the 2.4 km² surveillance frame. High-frequency X-band backscatter delineates hull geometries down to 0.5m GSD resolution, showing negligible wind-induced sea speckle.",
      targetInventory:
        "Classification identified: 3 Container Carriers (>220m), 5 Bulk Carriers (110–180m), 4 Coastal/Offshore Support Tugs, and 2 Unverified Compact Vessels. Target #3 exhibits a persistent metallic radar signature of +18.2 dBσ₀ with zero correlated AIS transmissions, qualifying as a Category-1 Priority Anomaly.",
      radarPhysics:
        "Calm water boundary generates near-perfect specular forward-scatter resulting in dark background (-21.4 dBσ₀). The orthogonal intersection of ship vertical hulls with the sea surface creates a classic double-bounce corner reflection, spiking backscatter up to +24.2 dBσ₀.",
      tacticalAdvisory:
        "Dispatch automatic cross-cueing tasking to optical constellations (e.g. Sentinel-2 / PlanetScope) over sector coordinates 1°14'N, 103°55'E for daytime optical hull ID confirmation on flagged dark target #3.",
    },
  },
  {
    id: "suvarnabhumi_airport",
    title: "Suvarnabhumi Airport Runways & Aircraft Apron Activity",
    location: "Bangkok International Airport",
    country: "Thailand",
    coordinates: {
      lat: "13°41'26.1\"N",
      lon: "100°44'56.3\"E",
    },
    filename: "sar_geotiff_10_suvarnabhumi_airport_umbra.tif",
    imageSrc: "/sar-samples/sar_geotiff_10_suvarnabhumi_airport_umbra.jpg",
    fileSize: "36.4 MB (GeoTIFF)",
    sensor: "Umbra X-SAR Constellation",
    mode: "Spotlight Precision Mode",
    polarization: "Single-Pol VV",
    resolution: "0.50 m GSD",
    frequency: "X-Band (9.6 GHz)",
    acquisitionDate: "2026-08-20 11:45:02 UTC",
    defaultPrompt:
      "Scan active runways 19L/01R, taxiways, and passenger boarding aprons. Detect commercial aircraft on tarmac, identify active FOD (foreign object debris) anomalies, and calculate gate occupancy percentage.",
    suggestedPrompts: [
      "Extract aircraft positions on apron parking gates and classify by fuselage size.",
      "Inspect runway centerlines for pavement surface roughness variations and debris.",
      "Measure terminal building metallic roof reflections and radar shadow geometry.",
      "Correlate tarmac ground service vehicle movement corridors.",
    ],
    summary:
      "High-resolution reconnaissance of primary runway corridors and passenger concourses, isolating 28 parked commercial airframes and checking runway surface integrity.",
    metrics: {
      totalTargets: 28,
      meanBackscatter: "-18.6 dBσ₀ (Runway Concrete)",
      peakBackscatter: "+28.5 dBσ₀ (Jet Engines / Fuselage)",
      surfaceArea: "6.25 km² Footprint",
      confidenceScore: "98.4% Multimodal Match",
    },
    detections: [
      {
        id: "det-air-1",
        label: "Wide-Body Aircraft (Boeing 777-300ER)",
        category: "aircraft",
        confidence: 0.98,
        x: 42.0,
        y: 38.5,
        width: 12.0,
        height: 10.5,
        details: "Prominent cavity reflection from twin high-bypass turbofan engines.",
        metrics: { length: "73.9m", beam: "64.8m", backscatterDb: 27.2, rcs: "48.0 dBsm" },
      },
      {
        id: "det-air-2",
        label: "Narrow-Body Aircraft (Airbus A320)",
        category: "aircraft",
        confidence: 0.96,
        x: 58.4,
        y: 44.0,
        width: 8.5,
        height: 7.8,
        details: "Parked at Gate D4 with jet-bridge docking apparatus engaged.",
        metrics: { length: "37.5m", beam: "35.8m", backscatterDb: 22.1, rcs: "36.2 dBsm" },
      },
      {
        id: "det-air-3",
        label: "Runway 19L Active Holding Point",
        category: "infrastructure",
        confidence: 0.99,
        x: 24.1,
        y: 62.0,
        width: 14.0,
        height: 6.0,
        details: "Surface asphalt smooth specular reflection (-24 dBσ₀). Zero FOD debris detected.",
        metrics: { length: "4000m", beam: "60m", backscatterDb: -23.8, rcs: "N/A" },
      },
      {
        id: "det-air-4",
        label: "Cargo Apron Logistics Cluster",
        category: "infrastructure",
        confidence: 0.93,
        x: 72.8,
        y: 28.5,
        width: 11.5,
        height: 9.0,
        details: "Dense grouping of container dollies and ground support vehicles.",
        metrics: { length: "120m", beam: "85m", backscatterDb: 16.4, rcs: "28.5 dBsm" },
      },
    ],
    analysisFindings: {
      executiveSummary:
        "Full spatial analysis of Suvarnabhumi Airport infrastructure confirms normal flight ops cadence. Identified 28 commercial aircraft across concourses A through G, with gate occupancy calculated at 76.4%.",
      targetInventory:
        "8 Wide-Body aircraft (B777/A350 class) and 20 Narrow-Body aircraft (A320/B737 class) successfully segmented. Runways 19L and 01R exhibit homogenous low backscatter signifying zero structural rutting or FOD blockage.",
      radarPhysics:
        "Smooth asphalt and grooved concrete pavements act as forward scatterers with minimal return (-24 dBσ₀). Metallic engine cowlings and vertical stabilizers create multi-path dihedral bounces (+28.5 dBσ₀) permitting sub-meter dimension verification.",
      tacticalAdvisory:
        "Runway safety threshold validated for all weather zero-visibility SAR ops. Maintain continuous 12-hour temporal baseline to track gate turnover rates.",
    },
  },
  {
    id: "panama_canal",
    title: "Panama Canal Lock Vessel Congestion & Transit Analysis",
    location: "Miraflores / Pedro Miguel Locks",
    country: "Panama",
    coordinates: {
      lat: "8°59'48.2\"N",
      lon: "79°35'27.5\"W",
    },
    filename: "sar_geotiff_11_panama_canal_umbra.tif",
    imageSrc: "/sar-samples/sar_geotiff_11_panama_canal_umbra.jpg",
    fileSize: "44.8 MB (GeoTIFF)",
    sensor: "Umbra X-SAR Constellation",
    mode: "Spotlight GeoTIFF",
    polarization: "Single-Pol VV",
    resolution: "0.50 m GSD",
    frequency: "X-Band (9.6 GHz)",
    acquisitionDate: "2026-08-18 16:10:44 UTC",
    defaultPrompt:
      "Analyze vessel queue density at lock approaches, quantify chamber water levels through multi-look radar intensity, and monitor structural integrity of lock gates.",
    suggestedPrompts: [
      "Count waiting Neopanamax container ships in Pacific queue basin.",
      "Check culvert lock gate alignment and culvert concrete wall backscatter.",
      "Measure canal fairway clearance and side bank vegetation encroachment.",
      "Estimate wait turnaround time based on lock chamber throughput.",
    ],
    summary:
      "Detailed SAR pass over Miraflores Lock chambers, revealing 9 transiting bulk vessels, operational water containment barriers, and approach queue distribution.",
    metrics: {
      totalTargets: 9,
      meanBackscatter: "-19.2 dBσ₀ (Canal Water)",
      peakBackscatter: "+26.1 dBσ₀ (Lock Gate Hinges)",
      surfaceArea: "4.80 km² Footprint",
      confidenceScore: "98.1% Multimodal Match",
    },
    detections: [
      {
        id: "det-pan-1",
        label: "Neopanamax Container Carrier in Lock Chamber",
        category: "vessel",
        confidence: 0.99,
        x: 48.2,
        y: 45.0,
        width: 15.0,
        height: 8.5,
        details: "Vessel constrained inside Miraflores upper lock chamber with electric mules engaged.",
        metrics: { length: "336m", beam: "49m", backscatterDb: 25.4, rcs: "52.1 dBsm" },
      },
      {
        id: "det-pan-2",
        label: "Lock Chamber Steel Mitre Gate",
        category: "infrastructure",
        confidence: 0.97,
        x: 56.5,
        y: 52.0,
        width: 8.2,
        height: 6.0,
        details: "Heavy steel gate in closed sealing position, showing zero radar leak or misalignment.",
        metrics: { length: "33m", beam: "20m", backscatterDb: 26.1, rcs: "38.0 dBsm" },
      },
      {
        id: "det-pan-3",
        label: "Pacific Approach Holding Queue #1",
        category: "vessel",
        confidence: 0.94,
        x: 22.0,
        y: 28.5,
        width: 11.0,
        height: 6.2,
        details: "Loaded Capesize ore carrier holding at southern fairway anchor.",
        metrics: { length: "290m", beam: "45m", backscatterDb: 21.8, rcs: "44.2 dBsm" },
      },
    ],
    analysisFindings: {
      executiveSummary:
        "Transit throughput monitoring over Miraflores Locks indicates steady single-file clearance. Currently 9 major cargo vessels are indexed across the immediate approach corridor.",
      targetInventory:
        "1 Neopanamax vessel inside chamber, 2 feeders navigating lower basin, and 6 large draft vessels queued at outer roadstead. Lock chamber hydraulic containment verified intact.",
      radarPhysics:
        "Vertical reinforced concrete chamber walls and steel mitre gates demonstrate massive corner-reflector scattering (+26 dBσ₀) contrasting cleanly against calm channeled fresh water (-19.2 dBσ₀).",
      tacticalAdvisory:
        "Transit clearance rate estimated at 1 vessel per 52 minutes. No geotechnical bank slumping or slope instability observed along canal cuts.",
    },
  },
  {
    id: "bingham_mine",
    title: "Bingham Canyon Open-Pit Mine Slope Stability & Machinery",
    location: "Oquirrh Mountains, Utah",
    country: "United States",
    coordinates: {
      lat: "40°31'24.8\"N",
      lon: "112°09'01.2\"W",
    },
    filename: "sar_geotiff_13_bingham_copper_mine_umbra.tif",
    imageSrc: "/sar-samples/sar_geotiff_13_bingham_copper_mine_umbra.jpg",
    fileSize: "62.6 MB (GeoTIFF)",
    sensor: "Umbra X-SAR Constellation",
    mode: "Spotlight Precision Mode",
    polarization: "Single-Pol VV",
    resolution: "0.50 m GSD",
    frequency: "X-Band (9.6 GHz)",
    acquisitionDate: "2026-08-11 19:30:10 UTC",
    defaultPrompt:
      "Evaluate open-pit terracing slope stability, map haul truck distribution along switchback ramps, and identify potential rockfall/shear plane zones.",
    suggestedPrompts: [
      "Delineate highwall bench terraces and detect millimeter-scale InSAR phase decorrelation.",
      "Classify heavy mining excavators and ultra-class haulage vehicles.",
      "Assess radar shadow zones caused by deep pit elevation gradients.",
      "Check tailings retention dam backscatter stability.",
    ],
    summary:
      "Deep open-pit copper quarry scan, mapping multi-level benches, switchback haul roads, and mining machinery operating across a 1,200m vertical profile.",
    metrics: {
      totalTargets: 16,
      meanBackscatter: "-7.8 dBσ₀ (Crushed Ore & Rock)",
      peakBackscatter: "+23.9 dBσ₀ (Heavy Electric Shovels)",
      surfaceArea: "8.50 km² Footprint",
      confidenceScore: "96.7% Multimodal Match",
    },
    detections: [
      {
        id: "det-min-1",
        label: "Electric Rope Shovel (CAT 7495)",
        category: "infrastructure",
        confidence: 0.97,
        x: 43.5,
        y: 52.1,
        width: 7.5,
        height: 6.8,
        details: "Massive metal gantry and boom scatterer on lower mining bench 4.",
        metrics: { length: "21m", beam: "13m", backscatterDb: 23.9, rcs: "38.7 dBsm" },
      },
      {
        id: "det-min-2",
        label: "Haul Truck Convoys on Ramp #2",
        category: "infrastructure",
        confidence: 0.94,
        x: 32.8,
        y: 38.0,
        width: 6.2,
        height: 5.4,
        details: "Three 400-ton Caterpillar 797F haul trucks in uphill transit.",
        metrics: { length: "15m", beam: "9.5m", backscatterDb: 19.2, rcs: "29.4 dBsm" },
      },
      {
        id: "det-min-3",
        label: "Highwall Bench Slope Segment",
        category: "terrain",
        confidence: 0.98,
        x: 62.0,
        y: 65.4,
        width: 13.0,
        height: 8.0,
        details: "Stable 42-degree rockface. Zero macroscopic tension cracks or slump scars.",
        metrics: { length: "350m", beam: "45m", backscatterDb: -5.4, rcs: "N/A" },
      },
    ],
    analysisFindings: {
      executiveSummary:
        "Geotechnical bench monitoring across Bingham Canyon pit reveals solid bench structural integrity. 11 haul trucks and 2 loading shovels mapped in active production zones.",
      targetInventory:
        "Bench slopes 1 through 12 exhibit normal roughness returns. Radar layover calibrated with DEM confirms steep slopes are within safe mechanical friction thresholds.",
      radarPhysics:
        "Rough fractured bedrock produces diffuse backscatter (-7.8 dBσ₀) while heavy mining steel produces high-intensity point targets (+23.9 dBσ₀). Steep walls cast distinct radar shadows useful for height profiling.",
      tacticalAdvisory:
        "All bench sectors stable. Continue daily InSAR differential phase tracking for early warning of highwall slope displacement.",
    },
  },
  {
    id: "komati_power",
    title: "Komati Power Station Critical Infrastructure & Coal Stockpile",
    location: "Mpumalanga",
    country: "South Africa",
    coordinates: {
      lat: "26°05'23.2\"S",
      lon: "29°28'19.4\"E",
    },
    filename: "sar_geotiff_12_komati_power_station_umbra.tif",
    imageSrc: "/sar-samples/sar_geotiff_12_komati_power_station_umbra.jpg",
    fileSize: "50.8 MB (GeoTIFF)",
    sensor: "Umbra X-SAR Constellation",
    mode: "Spotlight GeoTIFF",
    polarization: "Single-Pol VV",
    resolution: "0.50 m GSD",
    frequency: "X-Band (9.6 GHz)",
    acquisitionDate: "2026-08-16 08:15:30 UTC",
    defaultPrompt:
      "Assess power generation infrastructure, substation switchyard grid signatures, cooling tower structural backscatter, and coal stockyard volume contours.",
    suggestedPrompts: [
      "Inspect high-voltage transmission substation switchyards for structural anomalies.",
      "Verify cooling tower structural symmetry and concrete degradation.",
      "Estimate coal stockyard volumetric storage via radar shadow profiles.",
      "Monitor turbine hall perimeter security fence and access roads.",
    ],
    summary:
      "Critical energy infrastructure audit covering cooling towers, transformer yards, generation blocks, and coal handling conveyor networks.",
    metrics: {
      totalTargets: 12,
      meanBackscatter: "-11.2 dBσ₀ (Industrial Yard)",
      peakBackscatter: "+29.4 dBσ₀ (Substation Steel Busbars)",
      surfaceArea: "3.60 km² Footprint",
      confidenceScore: "97.5% Multimodal Match",
    },
    detections: [
      {
        id: "det-pow-1",
        label: "Hyperboloid Cooling Towers (Pair)",
        category: "infrastructure",
        confidence: 0.99,
        x: 45.0,
        y: 42.0,
        width: 14.5,
        height: 12.0,
        details: "Curved concrete shells exhibiting clean symmetrical radar returns. No structural spalling.",
        metrics: { length: "110m", beam: "85m", backscatterDb: 18.5, rcs: "42.0 dBsm" },
      },
      {
        id: "det-pow-2",
        label: "400kV Switchyard Grid & Transformers",
        category: "infrastructure",
        confidence: 0.98,
        x: 65.2,
        y: 55.4,
        width: 11.0,
        height: 8.5,
        details: "Dense lattice towers and transformer banks causing intense corner reflections.",
        metrics: { length: "180m", beam: "120m", backscatterDb: 29.4, rcs: "51.2 dBsm" },
      },
      {
        id: "det-pow-3",
        label: "Strategic Coal Stockyard Reserve",
        category: "terrain",
        confidence: 0.92,
        x: 25.8,
        y: 68.2,
        width: 12.5,
        height: 9.0,
        details: "Mounded bulk coal storage with distinct 28m radar shadow length.",
        metrics: { length: "240m", beam: "110m", backscatterDb: -9.8, rcs: "N/A" },
      },
    ],
    analysisFindings: {
      executiveSummary:
        "Infrastructure perimeter and generation blocks are intact. 400kV transmission switchyard energized and operational; coal reserves estimated at 410,000 metric tons.",
      targetInventory:
        "Identified 4 cooling towers, 1 central turbine generator hall, 2 primary switchyards, and 3 stacker-reclaimer conveyor arteries. No foreign intrusion or anomalous hot spots detected.",
      radarPhysics:
        "Curved concrete cooling tower shells provide continuous specular-to-diffuse backscatter gradient. Lattice metal substations create multiple dihedral and trihedral reflections (+29.4 dBσ₀).",
      tacticalAdvisory:
        "Stockyard reserves adequate for 38 days uninterrupted operation. Grid connection integrity rated nominal.",
    },
  },
  {
    id: "kilauea_volcano",
    title: "Kilauea Caldera Volcanic Subsidence & Lava Flow Delineation",
    location: "Hawaii Volcanoes National Park",
    country: "United States",
    coordinates: {
      lat: "19°25'16.4\"N",
      lon: "155°17'12.8\"W",
    },
    filename: "sar_geotiff_09_kilauea_volcano_hawaii_umbra.tif",
    imageSrc: "/sar-samples/sar_geotiff_09_kilauea_volcano_hawaii_umbra.jpg",
    fileSize: "22.2 MB (GeoTIFF)",
    sensor: "Umbra X-SAR Constellation",
    mode: "Spotlight Precision Mode",
    polarization: "Single-Pol VV",
    resolution: "0.50 m GSD",
    frequency: "X-Band (9.6 GHz)",
    acquisitionDate: "2026-08-09 05:40:12 UTC",
    defaultPrompt:
      "Delineate Halemaʻumaʻu crater floor deformation, identify fresh rough 'a'ā lava flows vs smooth pāhoehoe, and detect structural fissures along rift zones.",
    suggestedPrompts: [
      "Map surface roughness variation between rough basaltic clinker and smooth ropy lava.",
      "Isolate active crater rim fractures and quantify vertical caldera subsidence.",
      "Segment caldera thermal vent fractures from high-dielectric mineral deposits.",
      "Generate InSAR coherence map over the southwest rift zone.",
    ],
    summary:
      "Geomorphological radar mapping of Kilauea caldera and crater floor, categorizing rough vs smooth basaltic lava flows and rim fault scarps.",
    metrics: {
      totalTargets: 7,
      meanBackscatter: "-5.2 dBσ₀ (Rough 'A'ā Lava)",
      peakBackscatter: "+14.8 dBσ₀ (Fault Scarp Facets)",
      surfaceArea: "5.50 km² Footprint",
      confidenceScore: "96.4% Multimodal Match",
    },
    detections: [
      {
        id: "det-vol-1",
        label: "Rough 'A'ā Basaltic Flow Field",
        category: "terrain",
        confidence: 0.98,
        x: 48.0,
        y: 50.0,
        width: 18.0,
        height: 14.0,
        details: "Extremely rough surface on the order of X-band wavelength (3.1cm), causing high diffuse backscatter.",
        metrics: { length: "850m", beam: "600m", backscatterDb: -4.2, rcs: "N/A" },
      },
      {
        id: "det-vol-2",
        label: "Caldera Rim Fault Scarp",
        category: "terrain",
        confidence: 0.95,
        x: 28.5,
        y: 35.2,
        width: 12.0,
        height: 6.5,
        details: "Steep vertical rock displacement creating a bright lineament perpendicular to radar look angle.",
        metrics: { length: "420m", beam: "25m", backscatterDb: 14.8, rcs: "N/A" },
      },
      {
        id: "det-vol-3",
        label: "Smooth Pāhoehoe Crust Sector",
        category: "terrain",
        confidence: 0.93,
        x: 68.2,
        y: 62.0,
        width: 14.0,
        height: 10.0,
        details: "Glassy, smooth lava surface behaving as forward specular scatterer with lower return.",
        metrics: { length: "600m", beam: "450m", backscatterDb: -16.5, rcs: "N/A" },
      },
    ],
    analysisFindings: {
      executiveSummary:
        "Caldera geomorphology map highlights sharp roughness dichotomy. Rough blocky lava flows in the central crater floor exhibit strong returns, whereas peripheral glassy flows show low returns.",
      targetInventory:
        "Detected 3 major fault scarps, 2 active vent crater openings, and 1 extensive rough 'a'ā lava field. Caldera subsidence indicator shows stable baseline with zero catastrophic slump warning.",
      radarPhysics:
        "Surface roughness relative to X-band wavelength (3.1cm) drives backscatter: rough clinker scatters isotropically back to sensor (-4 dB), while smooth crust reflects energy away (-16.5 dB).",
      tacticalAdvisory:
        "USGS Volcano Hazards Alert remains at WATCH. Rim stability is adequate for research stations.",
    },
  },
  {
    id: "sydney_airport",
    title: "Sydney Airport Runway 16R Seawall & Aircraft Activity",
    location: "Mascot, Botany Bay",
    country: "Australia",
    coordinates: {
      lat: "33°56'46.1\"S",
      lon: "151°10'38.0\"E",
    },
    filename: "sar_geotiff_15_sydney_airport_umbra.tif",
    imageSrc: "/sar-samples/sar_geotiff_15_sydney_airport_umbra.jpg",
    fileSize: "69.7 MB (GeoTIFF)",
    sensor: "Umbra X-SAR Constellation",
    mode: "Spotlight Mode",
    polarization: "Single-Pol VV",
    resolution: "0.50 m GSD",
    frequency: "X-Band (9.6 GHz)",
    acquisitionDate: "2026-08-10 14:10:00 UTC",
    defaultPrompt:
      "Inspect Botany Bay runway extension seawall integrity, detect aircraft queued on taxiway Alpha, and map harbor channel navigation beacons.",
    suggestedPrompts: [
      "Analyze Runway 16R/34L reclaimed seawall concrete dolos armor blocks.",
      "Count passenger airframes lined up on taxiways during peak morning bank.",
      "Measure Botany Bay wave clutter intensity against airport revetments.",
    ],
    summary:
      "Botany Bay airport promontory high-resolution capture, showing ocean seawall defense structures and active runway tarmac.",
    metrics: {
      totalTargets: 22,
      meanBackscatter: "-19.8 dBσ₀ (Runway & Bay)",
      peakBackscatter: "+27.2 dBσ₀ (Aircraft Fuselages)",
      surfaceArea: "7.10 km² Footprint",
      confidenceScore: "98.0% Multimodal Match",
    },
    detections: [
      {
        id: "det-syd-1",
        label: "Commercial Aircraft on Runway 16R",
        category: "aircraft",
        confidence: 0.98,
        x: 48.0,
        y: 42.0,
        width: 10.0,
        height: 8.0,
        details: "Lined up for departure roll into Botany Bay heading.",
        metrics: { length: "63m", beam: "60m", backscatterDb: 26.5, rcs: "45.0 dBsm" },
      },
      {
        id: "det-syd-2",
        label: "Botany Bay Seawall Armor Blocks",
        category: "infrastructure",
        confidence: 0.99,
        x: 35.0,
        y: 72.0,
        width: 16.0,
        height: 6.0,
        details: "Concrete tetrapods and riprap preventing tidal scour on runway foundation.",
        metrics: { length: "1200m", beam: "25m", backscatterDb: 16.2, rcs: "N/A" },
      },
    ],
    analysisFindings: {
      executiveSummary:
        "Runway 16R seawall armor displays uniform reflection with zero seawall breaches. Identified 22 aircraft across airfield.",
      targetInventory:
        "1 aircraft on departure roll, 3 queued on taxiway Alpha, 18 at domestic/international gates.",
      radarPhysics:
        "Rough concrete seawall armor scatters strongly (+16 dBσ₀), isolating land-water interface with sub-meter accuracy.",
      tacticalAdvisory: "Seawall integrity nominal. No tidal overtopping or storm surge hazard detected.",
    },
  },
  {
    id: "buenos_aires",
    title: "Buenos Aires Puerto Madero & Rio de la Plata Urban Port",
    location: "Buenos Aires Harbor",
    country: "Argentina",
    coordinates: {
      lat: "34°36'12.0\"S",
      lon: "58°21'54.2\"W",
    },
    filename: "sar_geotiff_06_buenos_aires_umbra.tif",
    imageSrc: "/sar-samples/sar_geotiff_06_buenos_aires_umbra.jpg",
    fileSize: "18.3 MB (GeoTIFF)",
    sensor: "Umbra X-SAR Constellation",
    mode: "Spotlight Mode",
    polarization: "Single-Pol VV",
    resolution: "0.50 m GSD",
    frequency: "X-Band (9.6 GHz)",
    acquisitionDate: "2026-08-05 21:05:40 UTC",
    defaultPrompt:
      "Map urban building density, identify high-rise double-bounce cardinal angles, and track dockside container cranes along the Rio de la Plata basin.",
    suggestedPrompts: [
      "Segment dockside gantry cranes and cargo handling terminals.",
      "Extract urban street grid alignment relative to SAR radar line-of-sight.",
      "Monitor river estuary silt sediment backscatter patterns.",
    ],
    summary:
      "Urban port and high-rise financial district scan showing dense corner reflections from commercial towers and harbor docks.",
    metrics: {
      totalTargets: 31,
      meanBackscatter: "-8.4 dBσ₀ (Urban Built-up)",
      peakBackscatter: "+31.0 dBσ₀ (Container Cranes)",
      surfaceArea: "4.50 km² Footprint",
      confidenceScore: "97.2% Multimodal Match",
    },
    detections: [
      {
        id: "det-ba-1",
        label: "Puerto Madero Container Gantry Cranes",
        category: "infrastructure",
        confidence: 0.97,
        x: 42.0,
        y: 48.0,
        width: 12.0,
        height: 7.0,
        details: "Lattice steel cranes with distinct multipath ground bounce.",
        metrics: { length: "80m", beam: "45m", backscatterDb: 31.0, rcs: "54.0 dBsm" },
      },
    ],
    analysisFindings: {
      executiveSummary:
        "Urban footprint successfully delineated. Gantry cranes and container yards in active loading state; port fairway clear of obstruction.",
      targetInventory: "14 container cranes, 6 cargo vessels at berth, dense grid of high-rise commercial structures.",
      radarPhysics:
        "Urban building facades orthogonal to the radar beam create extreme double-bounce reflections exceeding +30 dBσ₀.",
      tacticalAdvisory: "Port operations normal. Basin fairway navigability confirmed.",
    },
  },
  {
    id: "centerfield_utah",
    title: "Centerfield Utah Agricultural Pivot Irrigation & Crop Vigor",
    location: "Sanpete County, Utah",
    country: "United States",
    coordinates: {
      lat: "39°04'12.0\"N",
      lon: "111°48'36.0\"W",
    },
    filename: "sar_geotiff_04_centerfield_utah_umbra.tif",
    imageSrc: "/sar-samples/sar_geotiff_04_centerfield_utah_umbra.jpg",
    fileSize: "13.1 MB (GeoTIFF)",
    sensor: "Umbra X-SAR Constellation",
    mode: "Spotlight Mode",
    polarization: "Single-Pol VV",
    resolution: "0.50 m GSD",
    frequency: "X-Band (9.6 GHz)",
    acquisitionDate: "2026-08-01 10:15:20 UTC",
    defaultPrompt:
      "Delineate circular center-pivot irrigation fields, assess crop canopy soil moisture dielectric response, and detect farm infrastructure.",
    suggestedPrompts: [
      "Classify irrigated vs non-irrigated circular crop parcels.",
      "Estimate topsoil dielectric constant linked to moisture content.",
      "Identify agricultural storage silos and pivot mechanical arms.",
    ],
    summary:
      "Classic circular center-pivot agricultural mosaic, demonstrating soil moisture dielectric contrasts in semi-arid terrain.",
    metrics: {
      totalTargets: 18,
      meanBackscatter: "-12.5 dBσ₀ (Vegetated Fields)",
      peakBackscatter: "+21.2 dBσ₀ (Metal Grain Silos)",
      surfaceArea: "5.00 km² Footprint",
      confidenceScore: "96.1% Multimodal Match",
    },
    detections: [
      {
        id: "det-cen-1",
        label: "Center-Pivot Irrigated Alfalfa Field",
        category: "terrain",
        confidence: 0.96,
        x: 50.0,
        y: 50.0,
        width: 22.0,
        height: 22.0,
        details: "High dielectric water content increases surface backscatter by 6.2 dB relative to dry fallow parcel.",
        metrics: { length: "800m dia", beam: "800m dia", backscatterDb: -9.1, rcs: "N/A" },
      },
    ],
    analysisFindings: {
      executiveSummary:
        "Vegetation moisture mapping completed across 28 center-pivot parcels. Moist irrigated crops show significantly heightened dielectric returns.",
      targetInventory: "18 active irrigated pivots, 6 fallow plots, 12 metallic farm structures.",
      radarPhysics:
        "Water's high dielectric constant (approx 80 vs 4 for dry soil) creates an unmistakable brightness jump in irrigated circles.",
      tacticalAdvisory: "Water usage efficiency index evaluated at 84.6%. No drought stress flags in active parcels.",
    },
  },
  {
    id: "melbourne_australia",
    title: "Melbourne Urban Infrastructure & Yarra River Corridor",
    location: "Melbourne CBD, Victoria",
    country: "Australia",
    coordinates: {
      lat: "37°49'02.0\"S",
      lon: "144°57'45.0\"E",
    },
    filename: "sar_geotiff_14_melbourne_australia_umbra.tif",
    imageSrc: "/sar-samples/sar_geotiff_14_melbourne_australia_umbra.jpg",
    fileSize: "62.6 MB (GeoTIFF)",
    sensor: "Umbra X-SAR Constellation",
    mode: "Spotlight Mode",
    polarization: "Single-Pol VV",
    resolution: "0.50 m GSD",
    frequency: "X-Band (9.6 GHz)",
    acquisitionDate: "2026-08-04 18:25:33 UTC",
    defaultPrompt:
      "Map transport bridges across the Yarra River, track rail yard locomotive concentrations, and assess high-density skyscraper radar shadow extent.",
    suggestedPrompts: [
      "Segment river bridges and evaluate steel truss structural backscatter.",
      "Analyze Southern Cross rail junction tracks and train car clusters.",
      "Calculate skyscraper heights from radar shadow elongation.",
    ],
    summary:
      "Dense metropolitan landscape spanning the Yarra River, railway junctions, and skyscraper cores with intricate radar shadows.",
    metrics: {
      totalTargets: 26,
      meanBackscatter: "-7.4 dBσ₀ (CBD Core)",
      peakBackscatter: "+32.4 dBσ₀ (Steel Bridges & Towers)",
      surfaceArea: "6.80 km² Footprint",
      confidenceScore: "97.9% Multimodal Match",
    },
    detections: [
      {
        id: "det-mel-1",
        label: "Yarra River Road/Rail Bridges",
        category: "infrastructure",
        confidence: 0.99,
        x: 46.0,
        y: 52.0,
        width: 14.0,
        height: 6.0,
        details: "High structural steel return spanning across specular low-return river surface.",
        metrics: { length: "160m", beam: "22m", backscatterDb: 28.5, rcs: "49.0 dBsm" },
      },
    ],
    analysisFindings: {
      executiveSummary:
        "Urban infrastructure mapping validates bridge clearances and transit hub density. Steel trusses stand out sharply against water.",
      targetInventory: "5 major bridges, 32 high-rise towers, 1 central rail interchange.",
      radarPhysics:
        "Multipath bounce between road decks and water surface creates intense line signature spanning the river channel.",
      tacticalAdvisory: "All arterial bridges structurally verified. River fairway unobstructed.",
    },
  },
  {
    id: "yapacana_venezuela",
    title: "Yapacana River Morphology & Dense Rainforest Canopy",
    location: "Amazonas",
    country: "Venezuela",
    coordinates: {
      lat: "3°45'00.0\"N",
      lon: "66°48'00.0\"W",
    },
    filename: "sar_geotiff_05_yapacana_venezuela_umbra.tif",
    imageSrc: "/sar-samples/sar_geotiff_05_yapacana_venezuela_jpg.jpg", // will fall back to jpg
    fileSize: "13.1 MB (GeoTIFF)",
    sensor: "Umbra X-SAR Constellation",
    mode: "Spotlight Mode",
    polarization: "Single-Pol VV",
    resolution: "0.50 m GSD",
    frequency: "X-Band (9.6 GHz)",
    acquisitionDate: "2026-07-28 09:30:00 UTC",
    defaultPrompt:
      "Delineate meandering river channel boundaries through dense tropical rainforest canopy and detect unauthorized alluvial mining clearings.",
    suggestedPrompts: [
      "Isolate river sandbars and seasonal flood bank changes.",
      "Detect illegal gold mining dredge equipment along river bends.",
      "Classify dense canopy volume scattering vs bare ground clearing.",
    ],
    summary:
      "Tropical rainforest river corridor with deep canopy volume scattering and winding sediment-laden river reaches.",
    metrics: {
      totalTargets: 8,
      meanBackscatter: "-8.9 dBσ₀ (Forest Canopy)",
      peakBackscatter: "+17.2 dBσ₀ (River Dredge Equipment)",
      surfaceArea: "4.20 km² Footprint",
      confidenceScore: "95.8% Multimodal Match",
    },
    detections: [
      {
        id: "det-yap-1",
        label: "Meandering River Channel",
        category: "water",
        confidence: 0.98,
        x: 45.0,
        y: 48.0,
        width: 25.0,
        height: 15.0,
        details: "Clean water-land interface delineated despite thick jungle foliage.",
        metrics: { length: "2400m", beam: "140m", backscatterDb: -22.0, rcs: "N/A" },
      },
    ],
    analysisFindings: {
      executiveSummary:
        "Tropical hydrology analysis accurately cuts through frequent Amazonian cloud cover to delineate river channel morphology.",
      targetInventory: "1 major river reach, 4 sandbank islands, 2 suspected artisanal dredging camps.",
      radarPhysics:
        "X-band scatters off top canopy leaves (-8.9 dBσ₀) while calm water surface mirrors signal away (-22 dBσ₀).",
      tacticalAdvisory: "Coordinates flagged for national park environmental protection agency inspection.",
    },
  },
  {
    id: "papua_indonesia",
    title: "Papua Indonesia Mountain Topography & Forest Canopy",
    location: "Papua Province",
    country: "Indonesia",
    coordinates: {
      lat: "4°15'00.0\"S",
      lon: "138°45'00.0\"E",
    },
    filename: "sar_geotiff_08_papua_indonesia_umbra.tif",
    imageSrc: "/sar-samples/sar_geotiff_08_papua_indonesia_umbra.jpg",
    fileSize: "22.2 MB (GeoTIFF)",
    sensor: "Umbra X-SAR Constellation",
    mode: "Spotlight Mode",
    polarization: "Single-Pol VV",
    resolution: "0.50 m GSD",
    frequency: "X-Band (9.6 GHz)",
    acquisitionDate: "2026-07-22 04:10:00 UTC",
    defaultPrompt:
      "Map rugged mountain ridge elevation relief, correct radar foreshortening, and isolate high-altitude logging roads through primary canopy.",
    suggestedPrompts: [
      "Correct severe topographic layover on steep foreslopes.",
      "Extract mountain ridge crests and drainage divide networks.",
      "Detect linear canopy clearings associated with road construction.",
    ],
    summary:
      "Rugged tropical mountain terrain exhibiting dramatic radar layover, shadow, and dense volumetric forest scattering.",
    metrics: {
      totalTargets: 6,
      meanBackscatter: "-7.1 dBσ₀ (Mountain Canopy)",
      peakBackscatter: "+18.9 dBσ₀ (Exposed Ridge Facets)",
      surfaceArea: "5.80 km² Footprint",
      confidenceScore: "95.2% Multimodal Match",
    },
    detections: [
      {
        id: "det-pap-1",
        label: "Rugged Ridge Crest & Foreslope",
        category: "terrain",
        confidence: 0.96,
        x: 45.0,
        y: 40.0,
        width: 20.0,
        height: 12.0,
        details: "Illuminated foreslope causing compression (foreshortening).",
        metrics: { length: "1200m", beam: "300m", backscatterDb: 15.4, rcs: "N/A" },
      },
    ],
    analysisFindings: {
      executiveSummary:
        "High-altitude SAR terrain analysis maps complex mountain ridges with cloud-penetrating radar clarity.",
      targetInventory: "4 major ridge crests, 2 drainage valleys, zero unauthorized logging roads.",
      radarPhysics:
        "Steep terrain creates foreshortening where top of mountain is received before base, producing bright illuminated facets.",
      tacticalAdvisory: "Topography stable; no recent catastrophic landslides identified.",
    },
  },
  {
    id: "tanna_island",
    title: "Tanna Island Vanuatu Coastal Fringing Reef & Volcano Flank",
    location: "Tafea Province",
    country: "Vanuatu",
    coordinates: {
      lat: "19°31'00.0\"S",
      lon: "169°18'00.0\"E",
    },
    filename: "sar_geotiff_01_tanna_island_vanuatu_umbra.tif",
    imageSrc: "/sar-samples/sar_geotiff_01_tanna_island_vanuatu_umbra.jpg",
    fileSize: "10.2 MB (GeoTIFF)",
    sensor: "Umbra X-SAR Constellation",
    mode: "Spotlight Mode",
    polarization: "Single-Pol VV",
    resolution: "0.50 m GSD",
    frequency: "X-Band (9.6 GHz)",
    acquisitionDate: "2026-07-15 12:00:00 UTC",
    defaultPrompt:
      "Map coastal fringing reef surf zones, volcanic ash deposits along Mount Yasur flanks, and detect isolated coastal village settlements.",
    suggestedPrompts: [
      "Extract shoreline waterline contour at high tide.",
      "Analyze ash plume ground fallout and vegetation die-back.",
      "Assess wave breaker sea clutter against shallow coral heads.",
    ],
    summary:
      "Pacific island coastline and volcanic slopes, delineating coral reef surf breaks and ash-mantled terrain.",
    metrics: {
      totalTargets: 5,
      meanBackscatter: "-14.2 dBσ₀ (Volcanic Sand & Ocean)",
      peakBackscatter: "+15.6 dBσ₀ (Breaking Surf & Coral)",
      surfaceArea: "3.20 km² Footprint",
      confidenceScore: "96.0% Multimodal Match",
    },
    detections: [
      {
        id: "det-tan-1",
        label: "Coastal Fringing Reef Surf Zone",
        category: "water",
        confidence: 0.95,
        x: 48.0,
        y: 62.0,
        width: 18.0,
        height: 8.0,
        details: "Breaking waves generate rough foam surfaces creating high radar backscatter.",
        metrics: { length: "950m", beam: "60m", backscatterDb: 12.1, rcs: "N/A" },
      },
    ],
    analysisFindings: {
      executiveSummary:
        "Coastal reef boundary and shoreline successfully extracted. Ash deposits from Mount Yasur clearly distinguishable.",
      targetInventory: "1 primary coral reef barrier, 2 coastal landing beaches, 1 volcanic ash deposit field.",
      radarPhysics:
        "Rough breaking surf creates turbulent foam with high diffuse backscatter contrasting against calm coastal lagoon.",
      tacticalAdvisory: "Tsunami evacuation routes and beach access points verified intact.",
    },
  },
];

// Fix for Yapacana filename if needed
SAR_DATASETS[9].imageSrc = "/sar-samples/sar_geotiff_05_yapacana_venezuela_umbra.jpg";

export const INITIAL_CHAT_SESSIONS: ChatSession[] = [
  {
    id: "chat-1",
    heading: "Maritime Vessel Recon & Dark Fleet Anomaly (Malacca)",
    category: "Maritime",
    date: "Today, 14:20",
    datasetId: "ship_detection",
    hasExecuted: true,
  },
  {
    id: "chat-2",
    heading: "Suvarnabhumi Airport Runways & Aircraft Apron Scan",
    category: "Aviation",
    date: "Today, 11:45",
    datasetId: "suvarnabhumi_airport",
    hasExecuted: true,
  },
  {
    id: "chat-3",
    heading: "Panama Canal Lock Vessel Congestion & Transit Delays",
    category: "Maritime",
    date: "Today, 09:12",
    datasetId: "panama_canal",
    hasExecuted: true,
  },
  {
    id: "chat-4",
    heading: "Bingham Canyon Open-Pit Mine Highwall Bench Stability",
    category: "Mining",
    date: "Yesterday",
    datasetId: "bingham_mine",
    hasExecuted: true,
  },
  {
    id: "chat-5",
    heading: "Komati Power Station 400kV Substation & Coal Reserves",
    category: "Critical Infra",
    date: "Yesterday",
    datasetId: "komati_power",
    hasExecuted: true,
  },
  {
    id: "chat-6",
    heading: "Kilauea Caldera Volcanic Subsidence & Lava Field Flow",
    category: "Geohazards",
    date: "Sep 03",
    datasetId: "kilauea_volcano",
    hasExecuted: true,
  },
  {
    id: "chat-7",
    heading: "Sydney Airport Runway 16R Seawall & Tarmac Ops",
    category: "Aviation",
    date: "Sep 02",
    datasetId: "sydney_airport",
    hasExecuted: true,
  },
  {
    id: "chat-8",
    heading: "Buenos Aires Puerto Madero High-Rise & Harbor Docks",
    category: "Critical Infra",
    date: "Aug 29",
    datasetId: "buenos_aires",
    hasExecuted: true,
  },
];
