"use client";

import React from "react";
import {
  FileText,
  Download,
  Printer,
  X,
  ShieldCheck,
  Calendar,
  MapPin,
  AlertTriangle,
} from "lucide-react";
import { SarDataset } from "../types";

interface ReportModalProps {
  isOpen: boolean;
  onClose: () => void;
  dataset: SarDataset;
  userPrompt: string;
}

export const ReportModal: React.FC<ReportModalProps> = ({
  isOpen,
  onClose,
  dataset,
  userPrompt,
}) => {
  if (!isOpen) return null;

  const handlePrint = () => {
    window.print();
  };

  const handleDownloadText = () => {
    const reportContent = `================================================================================
SATQUERY AI • SAR MULTIMODAL INTELLIGENCE MISSION REPORT
SMART INDIA HACKATHON 2026 - GEOSPATIAL DEFENSE & DISASTER TRACK
================================================================================

MISSION METADATA
----------------
Report Reference   : SQ-SIH-${Math.floor(100000 + Math.random() * 900000)}
Target Location    : ${dataset.title} (${dataset.location}, ${dataset.country})
Coordinates        : Lat ${dataset.coordinates.lat} | Lon ${dataset.coordinates.lon}
Sensor Platform    : ${dataset.sensor}
Operating Mode     : ${dataset.mode}
Polarization       : ${dataset.polarization}
Spatial Resolution : ${dataset.resolution}
Radar Frequency    : ${dataset.frequency}
Acquisition Time   : ${dataset.acquisitionDate}
Original File      : ${dataset.filename} (${dataset.fileSize})

QUERY PROMPT
------------
"${userPrompt || dataset.defaultPrompt}"

ANALYSIS METRICS & TARGET INVENTORY
-----------------------------------
Total Targets Detected : ${dataset.metrics.totalTargets}
Mean Sea/Terrain σ₀    : ${dataset.metrics.meanBackscatter}
Peak Return            : ${dataset.metrics.peakBackscatter}
Footprint Monitored    : ${dataset.metrics.surfaceArea}
Classification Match   : ${dataset.metrics.confidenceScore}

DETECTED OBJECTS
----------------
${dataset.detections
  .map(
    (d, i) =>
      `[${i + 1}] ${d.label} (Conf: ${(d.confidence * 100).toFixed(1)}%)\n    - Details : ${
        d.details
      }\n    - Metrics : Length: ${d.metrics?.length || "N/A"} | Beam: ${
        d.metrics?.beam || "N/A"
      } | RCS: ${d.metrics?.rcs || "N/A"}`
  )
  .join("\n")}

EXECUTIVE SUMMARY
-----------------
${dataset.analysisFindings.executiveSummary}

DETAILED TARGET FINDINGS
------------------------
${dataset.analysisFindings.targetInventory}

SAR RADAR PHYSICS & SCATTERING SIGNATURE
----------------------------------------
${dataset.analysisFindings.radarPhysics}

TACTICAL ADVISORY & RECOMMENDATIONS
-----------------------------------
${dataset.analysisFindings.tacticalAdvisory}

================================================================================
Generated by SatQuery AI Multimodal InSAR Analytics Engine
SIH 2026 Innovation Prototype
================================================================================`;

    const blob = new Blob([reportContent], { type: "text/plain;charset=utf-8" });
    const url = URL.createObjectURL(blob);
    const link = document.createElement("a");
    link.href = url;
    link.download = `SatQuery_SAR_Report_${dataset.id}_${Date.now()}.txt`;
    document.body.appendChild(link);
    link.click();
    document.body.removeChild(link);
    URL.revokeObjectURL(url);
  };

  return (
    <div className="fixed inset-0 z-50 flex items-center justify-center p-4 bg-black/40 backdrop-blur-xs">
      <div className="relative w-full max-w-3xl max-h-[90vh] bg-[#ffffff] border border-[#ded6c5] rounded-sm flex flex-col overflow-hidden text-[#232220] shadow-2xl">
        {/* Header */}
        <div className="flex items-center justify-between px-5 py-3.5 border-b border-[#ded6c5] bg-[#ede7dc]">
          <div className="flex items-center gap-2.5">
            <div className="w-7 h-7 bg-[#b24316] flex items-center justify-center text-[#ffffff] rounded-sm">
              <FileText className="w-4 h-4" />
            </div>
            <div>
              <h2 className="text-sm font-semibold tracking-wide text-[#232220] font-claude flex items-center gap-2">
                SAR Mission Intelligence Dossier
                <span className="px-1.5 py-0.2 text-[9px] font-mono bg-[#fbeee8] text-[#b24316] border border-[#f2cdbc] font-ui">
                  SIH 2026
                </span>
              </h2>
              <p className="text-[10px] text-[#5f5b55] font-mono">
                SQ-SIH-{dataset.id.toUpperCase()}
              </p>
            </div>
          </div>
          <button
            onClick={onClose}
            className="p-1 rounded-sm text-[#5f5b55] hover:text-[#232220] hover:bg-[#ded6c5] transition-colors"
          >
            <X className="w-4 h-4" />
          </button>
        </div>

        {/* Content */}
        <div className="flex-1 overflow-y-auto p-5 space-y-5 font-claude text-xs leading-relaxed bg-[#ffffff]">
          {/* Banner */}
          <div className="p-3.5 border border-[#ded6c5] bg-[#fbf9f5] rounded-sm flex flex-wrap items-center justify-between gap-3">
            <div>
              <div className="text-[9px] uppercase font-ui tracking-wider text-[#b24316] font-semibold">
                Autonomous Target Extraction
              </div>
              <h1 className="text-sm font-bold text-[#232220] mt-0.5">{dataset.title}</h1>
              <div className="flex items-center gap-3 text-[10px] text-[#5f5b55] mt-1 font-ui">
                <span className="flex items-center gap-1">
                  <MapPin className="w-3 h-3 text-[#b24316]" />
                  {dataset.location}, {dataset.country}
                </span>
                <span className="flex items-center gap-1">
                  <Calendar className="w-3 h-3 text-[#b24316]" />
                  {dataset.acquisitionDate}
                </span>
              </div>
            </div>
            <span className="px-2 py-0.5 rounded-sm bg-[#ffffff] text-[#232220] border border-[#ded6c5] text-[10px] font-ui flex items-center gap-1.5">
              <ShieldCheck className="w-3 h-3 text-[#b24316]" />
              MATCH {dataset.metrics.confidenceScore}
            </span>
          </div>

          {/* SAR Image and Specs */}
          <div className="grid grid-cols-1 md:grid-cols-3 gap-3">
            <div className="md:col-span-1 border border-[#ded6c5] bg-[#ede7dc] relative h-40 md:h-auto rounded-sm overflow-hidden">
              {/* eslint-disable-next-line @next/next/no-img-element */}
              <img
                src={dataset.imageSrc}
                alt={dataset.title}
                className="w-full h-full object-cover filter contrast-125"
              />
            </div>
            <div className="md:col-span-2 grid grid-cols-2 gap-2 text-[#232220] font-ui">
              <div className="p-2.5 border border-[#ded6c5] bg-[#fbf9f5] rounded-sm">
                <span className="text-[9px] text-[#5f5b55] block font-mono">Sensor Platform</span>
                <span className="font-semibold text-[#232220]">{dataset.sensor}</span>
                <span className="text-[9px] text-[#b24316] block font-mono mt-0.5">{dataset.polarization}</span>
              </div>
              <div className="p-2.5 border border-[#ded6c5] bg-[#fbf9f5] rounded-sm">
                <span className="text-[9px] text-[#5f5b55] block font-mono">Center Coordinates</span>
                <span className="font-semibold text-[#232220] font-mono">{dataset.coordinates.lat}</span>
                <span className="text-[9px] text-[#5f5b55] block font-mono mt-0.5">{dataset.coordinates.lon}</span>
              </div>
              <div className="p-2.5 border border-[#ded6c5] bg-[#fbf9f5] rounded-sm">
                <span className="text-[9px] text-[#5f5b55] block font-mono">Targets Isolated</span>
                <span className="text-sm font-bold text-[#232220]">{dataset.metrics.totalTargets} Detected</span>
                <span className="text-[9px] text-[#b24316] block font-mono mt-0.5">Peak {dataset.metrics.peakBackscatter}</span>
              </div>
              <div className="p-2.5 border border-[#ded6c5] bg-[#fbf9f5] rounded-sm">
                <span className="text-[9px] text-[#5f5b55] block font-mono">Footprint Area</span>
                <span className="text-sm font-bold text-[#232220]">{dataset.metrics.surfaceArea}</span>
                <span className="text-[9px] text-[#5f5b55] block font-mono mt-0.5">Mean {dataset.metrics.meanBackscatter}</span>
              </div>
            </div>
          </div>

          {/* Detections Table */}
          <div className="space-y-1.5 font-ui">
            <h3 className="text-xs font-semibold uppercase tracking-wider text-[#232220] flex items-center gap-1.5">
              <span className="w-1.5 h-1.5 rounded-full bg-[#b24316]" />
              Target Inventory
            </h3>
            <div className="border border-[#ded6c5] rounded-sm overflow-hidden">
              <table className="w-full text-left text-[11px]">
                <thead className="bg-[#ede7dc] text-[#5f5b55] font-mono text-[9px] border-b border-[#ded6c5]">
                  <tr>
                    <th className="p-2">#</th>
                    <th className="p-2">Target Class</th>
                    <th className="p-2">Confidence</th>
                    <th className="p-2">Dimensions</th>
                    <th className="p-2">Intensity</th>
                  </tr>
                </thead>
                <tbody className="divide-y divide-[#ded6c5] bg-[#ffffff]">
                  {dataset.detections.map((item, idx) => (
                    <tr key={item.id}>
                      <td className="p-2 font-mono text-[#8c867c]">{idx + 1}</td>
                      <td className="p-2 font-medium text-[#232220] font-claude">
                        {item.label}
                        <span className="block text-[9px] text-[#5f5b55] font-ui">{item.details}</span>
                      </td>
                      <td className="p-2 font-mono text-[#232220]">
                        {(item.confidence * 100).toFixed(1)}%
                      </td>
                      <td className="p-2 font-mono text-[#5f5b55]">
                        {item.metrics?.length ? `${item.metrics.length} × ${item.metrics.beam}` : "Segmented"}
                      </td>
                      <td className="p-2 font-mono text-[#b24316]">
                        {item.metrics?.backscatterDb !== undefined
                          ? `+${item.metrics.backscatterDb} dB`
                          : "N/A"}
                      </td>
                    </tr>
                  ))}
                </tbody>
              </table>
            </div>
          </div>

          {/* Findings Text */}
          <div className="space-y-2">
            <div className="p-3 border border-[#ded6c5] bg-[#fbf9f5] rounded-sm">
              <h4 className="font-semibold text-[#b24316] text-[11px] uppercase font-ui mb-1">Executive Summary</h4>
              <p className="text-[#3a3734] leading-relaxed">{dataset.analysisFindings.executiveSummary}</p>
            </div>
            <div className="p-3 border border-[#ded6c5] bg-[#fbf9f5] rounded-sm">
              <h4 className="font-semibold text-[#232220] text-[11px] uppercase font-ui mb-1">Radar Physics & Backscatter Profile</h4>
              <p className="text-[#3a3734] leading-relaxed">{dataset.analysisFindings.radarPhysics}</p>
            </div>
            <div className="p-3 border border-[#f2cdbc] bg-[#fbeee8] rounded-sm">
              <h4 className="font-semibold text-[#b24316] text-[11px] uppercase font-ui mb-1 flex items-center gap-1.5">
                <AlertTriangle className="w-3.5 h-3.5" />
                Tactical & Operational Advisory
              </h4>
              <p className="text-[#232220] leading-relaxed font-medium">{dataset.analysisFindings.tacticalAdvisory}</p>
            </div>
          </div>
        </div>

        {/* Footer */}
        <div className="flex items-center justify-between px-5 py-3 border-t border-[#ded6c5] bg-[#ede7dc] font-ui">
          <span className="text-[10px] text-[#5f5b55] font-mono">
            SatQuery AI • SIH 2026 Evaluation Protocol
          </span>
          <div className="flex items-center gap-2">
            <button
              onClick={handlePrint}
              className="flex items-center gap-1.5 px-3 py-1.5 rounded-sm border border-[#ded6c5] bg-[#ffffff] hover:bg-[#fbf9f5] hover:border-[#b24316] text-[#232220] text-xs font-medium transition-colors"
            >
              <Printer className="w-3.5 h-3.5" />
              Print
            </button>
            <button
              onClick={handleDownloadText}
              className="flex items-center gap-2 px-3.5 py-1.5 rounded-sm bg-[#b24316] hover:bg-[#98350d] text-[#ffffff] text-xs font-medium border border-[#b24316] transition-colors cursor-pointer shadow-xs"
            >
              <Download className="w-3.5 h-3.5" />
              Download Report
            </button>
          </div>
        </div>
      </div>
    </div>
  );
};
